"""replace mahasiswa with matakuliah

Revision ID: 6ed5c8fee870
Revises: 520f9b59a60b
Create Date: 2025-11-25 07:35:35.573244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed5c8fee870'
down_revision = '520f9b59a60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matakuliah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_mk', sa.Text(), nullable=False),
    sa.Column('nama_mk', sa.Text(), nullable=False),
    sa.Column('sks', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matakuliah')),
    sa.UniqueConstraint('kode_mk', name=op.f('uq_matakuliah_kode_mk'))
    )
    op.drop_table('mahasiswa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mahasiswa',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nim', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('nama', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('jurusan', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tanggal_lahir', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('alamat', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mahasiswa')),
    sa.UniqueConstraint('nim', name=op.f('uq_mahasiswa_nim'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('matakuliah')
    # ### end Alembic commands ###
